- instructions.md
Adding a first pass on the instructions page. Also testing out pull requests!
> Add instructions page.

- index.md
We added our names to index.md
> Pull Request for first Assignment

- 2022-1/index.md
I fixed the appearance for my gifs.
> updated index

- 2022-1/index.md
Added info to the main webpage
Co-Authored-By: Gabriel Mauger <65745023+gabemauger@users.noreply.github.com>
> Updated CatCat Space Blaster to main page

- 2022-1/index.md
added one space so v1.0 link works
> Fixed formatting

- 2022-3/index.md
I inserted my PGP Team (solo) into the contents as a hyperlink, along with adding a section for my team with my name hyperlinked to my GitHub.
> Added Team Lamb with member R. Vargas

- 2022-3/index.md
Added my name to the team name "Sumptuous Skunk" in the index.md file.
> Updated index.md

- 2022-3/index.md
> Add group names and github profile links to index.md

- 2022-3/index.md
Added my name and user name after the team name.
> Add username

- 2022-3/index.md
Added my functional prototype to the class portfolio.
> Functional Prototype

- 2022-3/index.md
Added my project folder, Fat Bird, with the game in it. Added links for my repo, my playable game, the game's release page, and it's preview gif in index.md
> Added game release and updated index.md

- 2022-3/index.md
Made gif displaying the prototype build of Skarper smaller.
> Adjusted gif size

- 2022-3/index.md
added final release to portfolio.
> final release

- 2024-3/index.md
Added Team and members in the index file
> Team Bingo

- 2024-3/index.md
Zombie Bash team info inserted into readme for 2024
> update 2024-3 readme with team zombie bash info

- 2020-3/index.md
Reverts NMSU-DGD/nmsu-dgd.github.io#247
This merge edits the wrong file. You need to edit the index.md within the 2024-3 semester folder. This merge edits the index.md within the 2020-3 semester folder.
> Revert "updated index.md"

- 2024-3/index.md
added team name to index.md in 2024 folder
> adds team name

- 2024-3/index.md
> Added Team Details

- 2024-3/index.md
added version link and gif for Team Code Crasher's for Functional prototype 2
> Added version(v0.2) for team codecrasher's

- 2024-3/index.md
Siva Bonia and Joshua Wilson, please fix the table of contents
> Neon Dream-On

- 2024-3/index.md
> Update index.md from Team Boom!

- 2024-3/index.md
Updated index and added gif to art folder
> MovingIn v0.2

- 2024-3/index.md
Spacemarshall game - The Space Wonderer release game.
> Release v0.3
